feed/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = "feed"

urlpatterns = [
    path("", views.index, name="base"),
    # path('',views.addView,name=""),
    path("video/", views.feedView, name="video"),
    # path("", views.feedView, name="video"),
]

pblproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("feed.urls", namespace="feed")),
    path("student/", include("student.urls", namespace="student")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from . import views

app_name = "student"

urlpatterns = [
    path("add/", views.addView, name="addView"),
    path("feed/", views.demoShowFeed, name="demoFeed"),
    path("list/", views.StudentListView.as_view(), name="studentList"),
    path("update/<int:id>/", views.updateView, name="updateView"),
    path("detail/<int:id>/", views.detailView, name="detailView"),
    path("delete/<int:id>/", views.deleteView, name="deleteView"),
    path("delete-action/<int:id>/", views.deleteActionView, name="deleteAction"),
]

student/models.py
from django.db import models
from django.utils import timezone

import os


def path_and_rename(instance, filename):
    upload_to = "photos"
    filename = "{}.{}".format(instance.rollNo, "jpg")
    return os.path.join(upload_to, filename)


# # Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=50)
    rollNo = models.CharField(max_length=10, unique=True)
    photo = models.ImageField(upload_to=path_and_rename, blank=True)
    added_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        ordering = ["-added_at"]

    def __str__(self):
        return self.name

student/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from django.db import IntegrityError
from django.http import StreamingHttpResponse, HttpResponse
from django.core.files.images import ImageFile
from django.views.decorators.csrf import csrf_exempt
from django.views.generic.list import ListView
import cv2
import io
import face_recognition
from .models import Student


def gen_frames():  # generate frame by frame from camerapipe
    camera = cv2.VideoCapture(0)
    while True:
        # Capture frame-by-frame
        success, frame = camera.read()  # read the camera frame
        if not success:
            break
        else:
            ret, buffer = cv2.imencode(".jpg", frame)
            frame = buffer.tobytes()
            yield (b"--frame\r\n" b"Content-Type: image/jpeg\r\n\r\n" + frame + b"\r\n")


# Create your views here.
def demoShowFeed(request):
    cv2.destroyAllWindows()
    return StreamingHttpResponse(
        gen_frames(), content_type="multipart/x-mixed-replace; boundary=frame"
    )


@csrf_exempt
def addView(request):
    camera = cv2.VideoCapture(0)

    if request.method == "POST":
        data = request.POST
        success, image = camera.read()
        # Saves the frames with frame-count
        is_success, buffer = cv2.imencode(".jpg", image)
        s = Student(rollNo=data["roll"], name=data["name"])
        s.photo = ImageFile(io.BytesIO(buffer.tobytes()), name="temp.jpg")
        try:
            s.save()
            messages.success(request, "Successfully Added New Student")
        except IntegrityError:
            messages.error(
                request, f"Student with roll no {data['roll']} already exist"
            )

        # camera.clear()
        return redirect("student:addView")
    return render(request, template_name="student/index.html")


@csrf_exempt
def updateView(request, id):
    curr_student = Student.objects.get(id=id)
    if request.method == "POST":
        data = request.POST
        s = Student.objects.get(pk=id)
        s.name = data["name"]
        s.save()
        messages.success(
            request,
            "Successfully Updated - {} ({})".format(s.name, s.rollNo),
        )
        return redirect(reverse("student:studentList"))

    return render(
        request, template_name="student/update.html", context={"student": curr_student}
    )


def detailView(request, id):
    curr_student = Student.objects.get(id=id)
    return render(
        request,
        template_name="student/detailView.html",
        context={"student": curr_student},
    )


def deleteView(request, id):
    curr_student = Student.objects.get(id=id)
    return render(
        request, "student/delete_view.html", context={"student": curr_student}
    )


def deleteActionView(request, id):
    curr_student = Student.objects.get(id=id)
    context = {"student": curr_student, "deleted": True}
    messages.success(
        request,
        "Successfully Deleted - {} ({})".format(curr_student.name, curr_student.rollNo),
    )
    curr_student.delete()
    return redirect(reverse("student:studentList"))


class StudentListView(ListView):
    template_name = "student/list.html"
    queryset = Student.objects.all()
    context_object_name = "students"
    print()

student/templates/student/delete_view.html
{% extends "feed/index.html" %} {% block content %}
<section class="text-gray-600 body-font">
	<div class="container px-5 py-24 mx-auto">
		<div
			class="
				flex flex-col
				p-8
				bg-white
				shadow-md
				hover:shodow-lg
				rounded-2xl
			"
		>
			<div class="flex items-center justify-between">
				<div class="flex items-center">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						class="
							w-16
							h-16
							rounded-2xl
							p-3
							border border-blue-200
							text-blue-600
							bg-blue-100
						"
						fill="none"
						viewBox="0 0 24 24"
						stroke="currentColor"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
						></path>
					</svg>
					<div class="flex flex-col ml-3">
						<div class="font-medium leading-none">
							Are you sure ?
						</div>
						<p class="text-sm text-gray-600 leading-none mt-1">
							By clicking on delete you will remove data for
							<b> {{student.name}} - {{student.rollNo}} </b>
						</p>
					</div>
				</div>
				<a href="{% url 'student:deleteAction' student.id %}">
					<button
						mat-icon-button=""
						class="
							flex-no-shrink
							bg-white
							px-5
							ml-4
							py-2
							text-sm
							shadow-sm
							font-medium
							tracking-wider
							border-2 border-red-400
							text-red-400
							rounded-full
							hover:text-white
							hover:bg-red-500
						"
					>
						Delete
					</button>
				</a>
			</div>
		</div>
	</div>
</section>
{% endblock content %}

student/templates/student/detailView.html
{% extends "feed/index.html" %}{% block content %}
<section class="text-gray-600 body-font">
	<div
		class="
			container
			mx-auto
			flex
			px-5
			py-10
			items-center
			justify-center
			flex-col
		"
	>
		<div class="text-center lg:w-2/3 w-full py-5">
			<h1
				class="
					title-font
					sm:text-4xl
					text-3xl
					mb-4
					font-medium
					text-gray-900
				"
			>
				Student Details
			</h1>
		</div>
		<img
			class="
				lg:w-2/6
				md:w-3/6
				w-5/6
				mb-10
				object-cover object-center
				rounded
			"
			alt="hero"
			src="{{student.photo.url}}"
		/>
		<div class="text-center lg:w-2/3 w-full">
			<div class="lg:w-2/3 w-full mx-auto overflow-auto">
				<table class="table-auto w-full text-center whitespace-no-wrap">
					<tbody>
						<tr>
							<td class="px-4 py-3">
								<strong> Name </strong>
							</td>
							<td class="px-4 py-3">{{student.name}}</td>
						</tr>
						<tr>
							<td class="px-4 py-3">
								<strong> Roll No. </strong>
							</td>
							<td class="px-4 py-3">{{student.rollNo}}</td>
						</tr>
						<tr>
							<td class="px-4 py-3">
								<strong> Added At </strong>
							</td>
							<td class="px-4 py-3">{{student.added_at}}</td>
						</tr>
						<tr>
							<td class="px-4 py-3">
								<strong> Last edited </strong>
							</td>
							<td class="px-4 py-3">{{student.updated_at}}</td>
						</tr>
					</tbody>
				</table>
			</div>

			<div class="flex justify-center py-5">
				<a href="{% url 'student:updateView' student.id %}">
					<button
						class="
							mx-4
							inline-flex
							text-white
							bg-green-500
							border-0
							py-2
							px-6
							focus:outline-none
							hover:bg-indigo-600
							rounded
							text-lg
						"
					>
						Update
					</button>
				</a>
				<a
					class="mr-5 hover:text-gray-900"
					href='{% url "student:deleteView" student.id %}'
					><button
						class="
							inline-flex
							text-white
							bg-red-500
							border-0
							py-2
							px-6
							focus:outline-none
							hover:bg-indigo-600
							rounded
							text-lg
						"
					>
						Delete
					</button></a
				>
			</div>
		</div>
	</div>
</section>
{% endblock content %}

student/templates/student/index.html
{% extends 'feed/index.html' %} {% block add %}
<style>
	.alert-box {
		padding: 5px;
		color: white;
		border-radius: 5px;
	}
	.success {
		background-color: #1eae98;
	}
	.error {
		background-color: #f55c47;
	}
</style>
<div class="row container shadow">
	<div class="form-side lg:w-3/4 w-full mx-auto overflow-auto mt-5">
		<p class="form-title">Add Student To DataBase</p>
		{% if messages %}
		<ul class="messages">
			{% for message in messages %}
			<li class="{{ message.tags }} alert-box">{{ message }}</li>
			{% endfor %}
		</ul>
		{% endif %}

		<form action="{% url 'student:addView' %}" method="post">
			<div class="form-group">
				<input
					type="text"
					name="name"
					placeholder="Enter the name"
					required
				/>
			</div>
			{% comment %} <br />
			{% endcomment %}
			<div class="form-group">
				<input
					type="text"
					name="roll"
					placeholder="Enter roll no"
					required
				/>
			</div>
			<div class="form-group btn-group">
				<button
					type="submit"
					class="btn btn-success btn-primary-shadow"
				>
					Submit
				</button>
			</div>
		</form>
	</div>
	<div class="image-side">
		<img src="{% url 'student:demoFeed' %}" alt="Live Image" />
	</div>
</div>

{% endblock add %}

student/templates/student/list.html
{% extends 'feed/index.html' %} {% block content %}
<style>
	.alert-box {
		padding: 8px;
		color: white;
		border-radius: 5px;
		margin-bottom: 10px;
	}
	.success {
		background-color: #1eae98;
	}
	.error {
		background-color: #f55c47;
	}
</style>
<section class="text-gray-600 body-font">
		<div class="lg:w-3/4 w-full mx-auto mt-5">
		{% if messages %}
			<ul class="messages">
				{% for message in messages %}
				<li class="{{ message.tags }} alert-box">{{ message }}</li>
				{% endfor %}
			</ul>
		{% endif %}
			<table class="table-auto w-full text-left whitespace-no-wrap">
				<thead>
					<tr>
						<th
							class="
								px-4
								py-3
								title-font
								tracking-wider
								font-medium
								text-gray-900 text-sm
								bg-gray-100
								rounded-tl rounded-bl
							"
						>
							Image
						</th>
						<th
							class="
								px-4
								py-3
								title-font
								tracking-wider
								font-medium
								text-gray-900 text-sm
								bg-gray-100
							"
						>
							Name
						</th>
						<th
							class="
								px-4
								py-3
								title-font
								tracking-wider
								font-medium
								text-gray-900 text-sm
								bg-gray-100
							"
						>
							Roll No.
						</th>
						<th
							class="
								px-4
								py-3
								title-font
								tracking-wider
								font-medium
								text-gray-900 text-sm
								bg-gray-100
							"
						>
							Added at
						</th>
						<th
							class="
								px-4
								py-3
								title-font
								tracking-wider
								font-medium
								text-gray-900 text-sm
								bg-gray-100
							"
						>
							Actions
						</th>
						
					</tr>
				</thead>
				<tbody>
				{% for student in students %}
					<tr class="px-2 py-2">
						<td class="px-3 py-1 flex content-center"><img alt="testimonial" class="w-20 h-20 object-cover object-center rounded-full  border-2 border-green-500 bg-green-500 align-middle" src="{{student.photo.url}}"></td>
						<td class="px-3 py-1"> 
							<a href='{% url "student:detailView" student.id %}'>
								{{student.name|capfirst }}</td>
							</a>
						<td class="px-3 py-1">{{student.rollNo}}</td>
						<td class="px-3 py-1">{{student.added_at}}</td>
						<td> 	
						<a
				class="mr-5 hover:text-gray-900"
				href='{% url "student:updateView" student.id %}'
				><button class="inline-flex text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Update</button></a
			> 
						<a
				class="mr-5 hover:text-gray-900"
				href='{% url "student:deleteView" student.id %}'
				><button class="inline-flex text-white bg-red-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Delete</button></a>
						</td>
					</tr>
				{% endfor %}
					
				</tbody>
			</table>
		</div>
	</div>
</section>
{% endblock content %}

student/templates/student/update.html
{% extends 'feed/index.html' %} {% block content %}
<section class="text-gray-600 body-font">
	<div
		class="
			container
			mx-auto
			flex flex-col
			px-5
			py-5
			justify-center
			items-center
			text-green-500
		"
	>
		<h1
			class="
				title-font
				sm:text-4xl
				text-3xl
				mb-4
				font-medium
				text-gray-900
			"
		>
			Update Student
		</h1>
		<img
			class="
				lg:w-2/6
				md:w-3/6
				w-5/6
				mb-10
				object-cover object-center
				rounded
			"
			alt="hero"
			src="{{student.photo.url}}"
		/>
		<div
			class="w-full md:w-2/3 flex flex-col mb-16 items-center text-center"
		>
			<h1
				class="
					title-font
					sm:text-4xl
					text-3xl
					mb-4
					font-medium
					text-gray-900
				"
			>
				{{student.name}}
			</h1>
			<div class="form-side">
				<p class="form-title">Update Students</p>

				{% if messages %}
				<ul class="messages">
					{% for message in messages %}
					<li class="{{ message.tags }} alert-box">{{ message }}</li>
					{% endfor %}
				</ul>
				{% endif %}

				<form
					action="{% url  'student:updateView' student.id %}"
					method="post"
				>
					{% csrf_token %}
					<div class="mb-4">
						<label
							class="block text-gray-700 text-sm font-bold mb-2"
							for="username"
						>
							Student Name
						</label>
						<input
							name="name"
							required
							value="{{student.name}}"
							class="
								shadow
								appearance-none
								border
								rounded
								w-full
								py-2
								px-3
								text-gray-700
								leading-tight
								focus:outline-none
								focus:shadow-outline
							"
							id="username"
							type="text"
							placeholder="Student Name"
						/>
					</div>
					<div class="mb-4">
						<label
							class="block text-gray-700 text-sm font-bold mb-2"
							for="username"
						>
							Roll No
						</label>
						<input
							name="roll"
							value="{{student.rollNo}}"
							disabled
							class="
								shadow
								appearance-none
								border
								rounded
								w-full
								py-2
								px-3
								text-gray-700
								leading-tight
								focus:outline-none
								focus:shadow-outline
							"
							id="username"
							type="text"
							placeholder="Roll No"
						/>
					</div>

					<div class="form-group btn-group">
						<button
							type="submit"
							class="btn btn-success btn-primary-shadow"
						>
							Submit
						</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</section>
{% endblock content %}