feed/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views


app_name = "feed"

urlpatterns = [
    path("", views.index, name="base"),
    # path('',views.addView,name=""),
    path("video/", views.feedView, name="video"),
    # path("", views.feedView, name="video"),
]

pblproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("feed.urls", namespace="feed")),
    path("student/", include("student.urls", namespace="student")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path
from . import views

app_name = "student"

urlpatterns = [
    path("add/", views.addView, name="addView"),
    path("feed/", views.demoShowFeed, name="demoFeed"),
    path("list/", views.StudentListView.as_view(), name="studentList"),
    path("update/<int:id>/", views.updateView, name="updateView"),
    path("detail/<int:id>/", views.detailView, name="detailView"),
    path("delete/<int:id>/", views.deleteView, name="deleteView"),
    path("delete-action/<int:id>/", views.deleteActionView, name="deleteAction"),
]

feed/models.py
from django.db import models
from django.utils import timezone
import os

feed/views.py
from django.shortcuts import render
from django.http import StreamingHttpResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
import cv2
import io
from student.models import Student
from django.core.files.images import ImageFile
from PIL import Image
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.core.files.base import ContentFile
from .recognizer import gen_frames
from . import defdata
import face_recognition

# import face_detection
import numpy as np

# Create your views here.


# def gen_frames():  # generate frame by frame from camerapipe
#     camera = cv2.VideoCapture(0)  # use 0 for web camera
#     all_data = Student.objects.all()
#     print(len(all_data))
#     isFoundFlag = False
#     if len(all_data) > 0:

#         images, Names = defdata.define(all_data)
#         print(Names)
#         encodeListKnown = defdata.encodings(images)
#         while True:
#             # Capture frame-by-frame
#             success, frame = camera.read()  # read the camera frame
#             if not success:
#                 break
#             else:
#                 imgS = cv2.resize(frame, (0, 0), None, 0.25, 0.25)
#                 #  We can find multiple face so to give face locations and send it to encoding fucntion
#                 #  Encoding the capured image
#                 imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)

#                 faceCurr = face_recognition.face_locations(imgS)
#                 encodeCurr = face_recognition.face_encodings(imgS, faceCurr)

#                 # Finding matches
#                 for encodeFace, faceLoc in zip(encodeCurr, faceCurr):
#                     # matches gives bollean output if which of the face is matching
#                     matches = face_recognition.compare_faces(
#                         encodeListKnown, encodeFace
#                     )
#                     # the lower the face disatnce the better the match is
#                     faceDis = face_recognition.face_distance(
#                         encodeListKnown, encodeFace
#                     )
#                     # as we are giving list as input to faceDis we will get list as output
#                     # We will get 3 output as we have given 3 input and the lowest will be the match
#                     matchIndex = np.argmin(faceDis)

#                     if matches[matchIndex]:
#                         name = Names[matchIndex].upper()
#                         print(name)
#                         isFoundFlag = True
#                         y1, x2, y2, x1 = faceLoc
#                         y1, x2, y2, x1 = (
#                             y1 * 4,
#                             x2 * 4,
#                             y2 * 4,
#                             x1 * 4,
#                         )  # since we resized it we are incrasing the size
#                         cv2.rectangle(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)
#                         cv2.rectangle(
#                             frame, (x1, y2 - 35), (x2, y2), (0, 255, 0), cv2.FILLED
#                         )
#                         cv2.putText(
#                             frame,
#                             name,
#                             (x1 + 6, y2 - 6),
#                             cv2.FONT_HERSHEY_COMPLEX,
#                             1,
#                             (255, 255, 255),
#                             2,
#                         )

#             ret, buffer = cv2.imencode(".jpg", frame)
#             frame = buffer.tobytes()
#             yield b"--frame\r\n" b"Content-Type: image/jpeg\r\n\r\n" + frame + b"\r\n", isFoundFlag


def feedView(request):
    allStudents = Student.objects.all()
    found_studs = gen_frames()
    student_array = []
    found = False
    for each in found_studs:
        student_array.append(Student.objects.get(rollNo=each))
    if len(student_array) != 0:
        found = True
    print(student_array)
    print(found)
    return render(
        request, "feed/display_reco.html", {"students": student_array, "found": found}
    )


def detectView(request):
    fun, isFound = gen_frames()
    if isFound:
        value = 0
    else:
        value = 1
    return render(request, "feed/videoView.html")


def index(request):
    return render(request, "feed/hero.html")


# @csrf_exempt
# def index(request):
#     # all_data = Student.objects.all()

#     # print(all_data[0].photo)
#     if request.method == "POST":
#         data = request.POST
#         success, image = camera.read()
#         # Saves the frames with frame-count
#         is_success, buffer = cv2.imencode(".jpg", image)

#         s = Student(rollNo=data["roll"])
#         s.photo = ImageFile(io.BytesIO(buffer.tobytes()), name="temp.jpg")
#         s.save()
#         pass
#     return render(request, "feed/index.html")


#
# def addView(request):
#     if request.method == "POST":
#         current_image = cv2.imwrite('opencv.png', gen_frames)
#         print(current_image)
#

feed/templates/feed/display_reco.html
{% extends "feed/index.html" %} {% block content %}
<section class="text-gray-600 body-font">
	<div class="lg:w-3/4 w-full mx-auto overflow-auto mt-5">
		{% if found %}
		<h1 style="margin-bottom: 10px;">
			Recognized Students
		</h1>
		<table class="table-auto w-full text-left whitespace-no-wrap">
			<thead>
				<tr>
					<th
					class="
					px-4
					py-3
					title-font
					tracking-wider
					font-medium
					text-gray-900 text-sm
					bg-gray-100
					rounded-tl rounded-bl
					"
					>
					Image
				</th>
				<th
				class="
				px-4
				py-3
				title-font
				tracking-wider
				font-medium
				text-gray-900 text-sm
				bg-gray-100
				"
				>
				Name
			</th>
			<th
			class="
			px-4
			py-3
			title-font
			tracking-wider
			font-medium
			text-gray-900 text-sm
			bg-gray-100
			"
			>
			Roll No.
		</th>
		
		</tr>
				</thead>
				<tbody>
					
					{% for student in students %}
					<tr class="px-2 py-2">
						<td class="px-3 py-1 flex content-center"><img alt="testimonial" class="w-20 h-20 object-cover object-center rounded-full  border-2 border-green-500 bg-green-500 align-middle" src="{{student.photo.url}}"></td>
						<td class="px-3 py-1"> 
							<a href='{% url "student:detailView" student.id %}'>
								{{student.name|capfirst }}</td>
							</a>
							<td class="px-3 py-1">{{student.rollNo}}</td>
						</tr>
						{% endfor %}					  
					</tbody>
				</table>
		{% else %}
			<h1>No student recognized</h1>
		{% endif %}
		</div>
</section>
	{% endblock content %}
	

feed/templates/feed/hero.html
{% extends 'feed/index.html' %} {% load static %}{% block content %}
<section class="text-gray-600 body-font">
	<div
		class="
			container
			mx-auto
			flex
			px-5
			py-10
			md:flex-row
			flex-col
			items-center
		"
	>
		<div
			class="
				lg:flex-grow
				md:w-1/2
				lg:pr-24
				md:pr-16
				flex flex-col
				md:items-start
				md:text-left
				mb-16
				md:mb-0
				items-center
				text-center
			"
		>
			<h1
				class="
					title-font
					sm:text-4xl
					text-3xl
					mb-4
					font-medium
					text-gray-900
				"
			>
				Face Recognition System
				<br class="hidden lg:inline-block" />
			</h1>
			<p class="mb-8 leading-relaxed">
				Easy to use. Amazingly fast.Highly Scalable.New cutting edge
				technology to Recognize faces stored in your database.
			</p>
			<div class="flex justify-center">
				<a
					class="mr-5 hover:text-gray-900"
					href='{% url "student:addView" %}'
				>
					<button
						class="
							inline-flex
							text-white
							bg-indigo-500
							border-0
							py-2
							px-6
							focus:outline-none
							hover:bg-indigo-600
							rounded
							text-lg
						"
					>
						Get Started
					</button></a
				>
			</div>
		</div>
		<div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
			<img
				class="object-cover object-center rounded"
				alt="hero"
				src="{% static '/images/hero.jpg/' %}"
			/>
		</div>
	</div>
</section>
{% endblock content %}

feed/templates/feed/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>Face:Recognizer</title>
		<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
		<link rel="stylesheet" href="{% static '/css/styles.css/' %}" />
	</head>
	<body>
	{% include "feed/navbar.html" %}
	{% block display %}
	{% endblock display %}
		{% block content %}
		
		{% endblock content %}

			{% comment %} <img src='{% url "feed:video" %}' /> {% endcomment %}
		
			{% block add %}
			{% endblock add %}
			</form>
		</div>
	</body>
</html>

feed/templates/feed/navbar.html
<header class="text-gray-600 body-font">
	<div
		class="
			container
			mx-auto
			flex flex-wrap
			p-5
			flex-col
			md:flex-row
			items-center
		"
	>
		<a
			class="
				flex
				title-font
				font-medium
				items-center
				text-gray-900
				mb-4
				md:mb-0
			"
            href="{% url "feed:base" %}"
		>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				fill="none"
				stroke="currentColor"
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full"
				viewBox="0 0 24 24"
			>
				<path
					d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"
				></path>
			</svg>
			<span class="ml-3 text-xl">Face Reco</span>
		</a>
		<nav
			class="
				md:ml-auto
				flex flex-wrap
				items-center
				text-base
				justify-center
			"
		>
			<a
				class="mr-5 hover:text-gray-900"
				href='{% url "student:addView" %}'
				>Add Student</a
			>
			<a class="mr-5 hover:text-gray-900"
            	href="{% url "student:studentList" %}">Student List</a>
		</nav>
		<a href="{% url 'feed:video' %}">
			
			<button
			class="
				inline-flex
				items-center
				bg-purple-500
				border-0
				py-1
				px-3
				focus:outline-none
				hover:bg-gray-200
				rounded
				text-base
				mt-4
				md:mt-0
				"
				>
				Face Recognizer
				<svg
				fill="none"
				stroke="currentColor"
				stroke-linecap="round"
				stroke-linejoin="round"
				stroke-width="2"
				class="w-4 h-4 ml-1"
				viewBox="0 0 24 24"
				>
				<path d="M5 12h14M12 5l7 7-7 7"></path>
			</svg>
		</button>
	</a>
	</div>
</header>